name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

env:
  JAVA_OPTS: "-Xmx4G"

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Build
        run: |
          npm install
          sbt --client buildRelease

      - name: Build binaries
        run: | 
          npm install -g pkg
          pkg bin/grammar-js-lsp.js --out-path bin

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/*
      # - name: Publish ${{ github.ref }}
      #   if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')
      #   run: sbt ci-release
      #   env:
      #     PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      #     PGP_SECRET: ${{ secrets.PGP_SECRET }}
      #     SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      #     SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
